name: Monorepo Deploy (Heroku & Vercel)

on:
  push:
    branches:
      - main

jobs:
  deploy-backend-heroku:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Start Firebase Emulators
        run: npx firebase emulators:start --only firestore,auth --project demo-test --import=./emulator-data --export-on-exit=./emulator-data &
        working-directory: ./backend

      - name: Print npm debug log
        if: failure()
        run: cat /home/runner/.npm/_logs/*.log || true

      - name: Wait for Firestore Emulator
        run: npx wait-on tcp:8080

      - name: Run backend tests
        run: npm run test
        working-directory: ./backend
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          FIREBASE_AUTH_EMULATOR_HOST: localhost:8089
          FIREBASE_PROJECT_ID: demo-test
          FIREBASE_CREDENTIALS: '{}'

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'family-feud-backend'
          heroku_email: 'sheriff.jolaoso+heroku@gmail.com'
          branch: main
          usedocker: false

  deploy-frontend-vercel:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm run test:ci
        working-directory: ./frontend
        env:
          VITE_FIREBASE_CONFIG: ${{ secrets.VITE_FIREBASE_CONFIG }}
          VITE_USE_FIREBASE_EMULATOR: 'true'

      - name: Build (optional, for static sites)
        run: npm run build

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
